-- Data for "Catalog"."Categories"
-- Exported from SQL Server [Catalog].[Categories]

INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (1, 'Computadoras', 'Computers', 'Laptops, PCs y componentes', 'Laptops, PCs and components', 'computadoras', NULL, true, 1, true, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400');
INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (2, 'Perifericos', 'Peripherals', 'Teclados, ratones y accesorios', 'Keyboards, mice and accessories', 'perifericos', NULL, true, 2, true, 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400');
INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (3, 'Audio', 'Audio', 'Auriculares, microfonos y bocinas', 'Headphones, microphones and speakers', 'audio', NULL, true, 3, true, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400');
INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (4, 'Componentes', 'Components', 'Componentes internos para PC', 'Internal PC components', 'componentes', NULL, true, 4, true, 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400');
INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (5, 'Monitores', 'Monitors', 'Pantallas y monitores', 'Screens and monitors', 'monitores', NULL, true, 5, true, 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400');
INSERT INTO "Catalog"."Categories" ("CategoryId", "NameSpanish", "NameEnglish", "DescriptionSpanish", "DescriptionEnglish", "Slug", "ParentCategoryId", "IsActive", "DisplayOrder", "IsFeatured", "ImageUrl") VALUES (6, 'Mobiliario', 'Furniture', 'Sillas y escritorios gaming', 'Gaming chairs and desks', 'mobiliario', NULL, true, 6, true, 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400');
