-- Data for "Catalog"."AttributeValues"
-- Exported from SQL Server [Catalog].[AttributeValues]

INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1, 1, 'Negro', 'Black', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (2, 1, 'Blanco', 'White', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (3, 1, 'Azul', 'Blue', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (4, 1, 'Rojo', 'Red', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (5, 1, 'Gris', 'Gray', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (6, 1, 'Plateado', 'Silver', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (7, 2, '64 GB', '64GB', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (8, 2, '128 GB', '128GB', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (9, 2, '256 GB', '256GB', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (10, 2, '512 GB', '512GB', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (11, 2, '1 TB', '1TB', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (12, 3, '4 GB', '4GB', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (13, 3, '8 GB', '8GB', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (14, 3, '16 GB', '16GB', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (15, 3, '32 GB', '32GB', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (23, 5, '38', '38', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (24, 5, '39', '39', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (25, 5, '40', '40', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (26, 5, '41', '41', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (27, 5, '42', '42', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (28, 5, '43', '43', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (29, 6, 'Intel Core i5', 'i5', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (30, 6, 'Intel Core i7', 'i7', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (31, 6, 'Intel Core i9', 'i9', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (32, 6, 'Apple M1', 'M1', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (33, 6, 'Apple M2', 'M2', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (34, 6, 'Apple M3', 'M3', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (35, 6, 'AMD Ryzen 5', 'Ryzen 5', 7);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (36, 7, 'Full HD 1920x1080', 'FHD', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (37, 7, '4K Ultra HD', '4K', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (38, 7, '8K Ultra HD', '8K', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (39, 8, 'Wi-Fi', 'WiFi', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (40, 8, 'Bluetooth', 'Bluetooth', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (41, 8, 'USB-C', 'USB-C', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (42, 8, 'InalÃ¡mbrico', 'Wireless', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1001, 101, 'Negro', 'Black', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1002, 101, 'Blanco', 'White', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1003, 101, 'Azul', 'Blue', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1004, 101, 'Rojo', 'Red', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1005, 101, 'Gris', 'Gray', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1006, 101, 'Plateado', 'Silver', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1007, 102, '64 GB', '64GB', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1008, 102, '128 GB', '128GB', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1009, 102, '256 GB', '256GB', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1010, 102, '512 GB', '512GB', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1011, 102, '1 TB', '1TB', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1012, 103, '4 GB', '4GB', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1013, 103, '8 GB', '8GB', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1014, 103, '16 GB', '16GB', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1015, 103, '32 GB', '32GB', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1023, 105, '38', '38', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1024, 105, '39', '39', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1025, 105, '40', '40', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1026, 105, '41', '41', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1027, 105, '42', '42', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1028, 105, '43', '43', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1029, 106, 'Intel Core i5', 'i5', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1030, 106, 'Intel Core i7', 'i7', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1031, 106, 'Intel Core i9', 'i9', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1032, 106, 'Apple M2', 'M2', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1033, 106, 'Apple M3', 'M3', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1034, 106, 'AMD Ryzen 5', 'Ryzen 5', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1035, 107, 'Full HD 1920x1080', 'FHD', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1036, 107, '4K Ultra HD', '4K', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1037, 107, '8K Ultra HD', '8K', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1038, 108, 'Wi-Fi', 'WiFi', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1039, 108, 'Bluetooth', 'Bluetooth', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1040, 108, 'USB', 'USB', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1041, 108, 'InalÃ¡mbrico', 'Wireless', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1042, 109, '2024', '2024', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1043, 109, '2023', '2023', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1044, 109, '2022', '2022', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1045, 109, '2021', '2021', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1046, 109, '2020', '2020', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1047, 109, '2019', '2019', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1048, 109, '2018', '2018', 7);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1049, 110, 'Nuevo', 'New', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1050, 110, 'Renovado', 'Refurbished', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1051, 110, 'Usado', 'Used', 3);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1052, 111, 'Montaje en Mesa', 'Desk Mount', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1053, 111, 'Montaje en Pared', 'Wall Mount', 2);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1054, 108, 'HDMI', 'HDMI', 5);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1055, 108, 'Ethernet', 'Ethernet', 6);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1056, 107, 'HD 720p', 'HD 720p', 4);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1057, 106, 'Apple M1', 'Apple M1', 20);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1058, 106, 'Apple M4', 'Apple M4', 23);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1059, 112, 'Nuevo', 'New', 1);
INSERT INTO "Catalog"."AttributeValues" ("ValueId", "AttributeId", "ValueText", "ValueTextEnglish", "DisplayOrder") VALUES (1060, 112, 'Usado', 'Used', 2);
