-- Data for "Catalog"."ProductAttributes"
-- Exported from SQL Server [Catalog].[ProductAttributes]

INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (1, 'Color', 'Color', 'Select', NULL, true, false, 1, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (2, 'Almacenamiento', 'Storage', 'Select', 'GB', true, false, 2, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (3, 'Memoria RAM', 'RAM', 'Select', 'GB', true, false, 3, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (4, 'TamaÃ±o de Pantalla', 'Screen Size', 'Numeric', 'pulgadas', true, false, 4, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (5, 'Talla', 'Size', 'Select', NULL, true, false, 5, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (6, 'Procesador', 'Processor', 'Select', NULL, true, false, 6, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (7, 'ResoluciÃ³n', 'Resolution', 'Select', NULL, true, false, 7, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (8, 'Conectividad', 'Connectivity', 'MultiSelect', NULL, true, false, 8, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (101, 'Color', 'Color', 'Select', NULL, true, false, 1, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (102, 'Almacenamiento', 'Storage', 'Select', 'GB', true, false, 2, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (103, 'Memoria RAM', 'RAM', 'Select', 'GB', true, false, 3, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (104, 'TamaÃ±o de Pantalla', 'Screen Size', 'Numeric', 'pulgadas', true, false, 4, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (105, 'Talla', 'Size', 'Select', NULL, true, false, 5, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (106, 'Procesador', 'Processor', 'Select', NULL, true, false, 6, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (107, 'ResoluciÃ³n', 'Resolution', 'Select', NULL, true, false, 7, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (108, 'Conectividad', 'Connectivity', 'MultiSelect', NULL, true, false, 8, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (109, 'AÃ±o del Modelo', 'Model Year', 'Select', NULL, true, false, 9, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (110, 'CondiciÃ³n', 'Condition', 'Select', NULL, true, true, 10, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (111, 'Tipo de Montaje', 'Mount Type', 'MultiSelect', NULL, true, false, 11, NULL);
INSERT INTO "Catalog"."ProductAttributes" ("AttributeId", "AttributeName", "AttributeNameEnglish", "AttributeType", "Unit", "IsFilterable", "IsSearchable", "DisplayOrder", "CategoryId") VALUES (112, 'Condicion', 'Condition', 'Select', NULL, true, true, 2, NULL);
