-- Data for order.paymenttypes
-- Exported from SQL Server [Order].[PaymentTypes]

INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (0, 'CreditCard', 'Tarjeta de CrÃ©dito', 'Pago con tarjeta de crÃ©dito', 'credit_card', true, 1, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (1, 'DebitCard', 'Tarjeta de DÃ©bito', 'Pago con tarjeta de dÃ©bito', 'payment', true, 2, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (2, 'MercadoPago', 'MercadoPago', 'Pago a travÃ©s de MercadoPago', 'account_balance_wallet', true, 3, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (3, 'PayPal', 'PayPal', 'Pago a travÃ©s de PayPal', 'account_balance', true, 4, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (4, 'BankTransfer', 'Transferencia Bancaria', 'Transferencia bancaria directa', 'account_balance', true, 5, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (5, 'Cash', 'Efectivo', 'Pago en efectivo', 'local_atm', true, 6, '2025-11-26 00:28:02.300');
INSERT INTO order."PaymentTypes" ("PaymentTypeId", "PaymentTypeName", "PaymentTypeNameEs", "Description", "IconName", "IsActive", "DisplayOrder", "CreatedAt") VALUES (99, 'Other', 'Otro', 'Otro mÃ©todo de pago', 'more_horiz', true, 7, '2025-11-26 00:28:02.300');
