-- Data for payment.paymenttransactions
-- Exported from SQL Server [Payment].[PaymentTransactions]

INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (5, 20, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-26 01:27:32.387', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (6, 21, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-26 01:30:47.555', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (7, 38, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 05:14:12.162', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (8, 39, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 05:41:51.914', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (9, 40, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 05:44:12.261', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (10, 41, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 05:49:14.992', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (11, 42, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:14:13.946', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (12, 43, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:19:25.421', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (13, 44, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:25:02.610', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (14, 45, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:29:15.491', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (15, 46, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:32:35.686', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (16, 47, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:36:27.430', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (17, 48, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:42:46.435', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (18, 49, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:46:41.195', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (19, 50, 1, 74277.60, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 06:52:33.837', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (20, 52, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 07:13:59.641', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (21, 53, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 07:15:01.876', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (22, 54, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 07:18:18.388', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (23, 55, 1, 37138.80, 2, NULL, 'Payment amount exceeds test limit (9999). Use lower amount for successful test.', '2025-11-27 07:33:07.149', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (24, 57, 1, 478.51, 2, NULL, 'Rechazado por fecha de expiración inválida', '2025-12-13 21:38:15.177', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (25, 60, 1, 478.51, 2, NULL, 'Rechazado - Llamar para autorizar', '2025-12-13 21:47:10.985', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (26, 61, 1, 478.51, 2, NULL, 'Rechazado por error general', '2025-12-13 22:01:42.008', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (27, 65, 1, 6847.10, 2, NULL, 'Rechazado - Llamar para autorizar', '2025-12-14 06:46:15.229', NULL);
INSERT INTO payment."PaymentTransactions" ("TransactionId", "PaymentId", "TransactionType", "Amount", "Status", "GatewayResponse", "ErrorMessage", "TransactionDate", "IPAddress") VALUES (28, 67, 1, 478.51, 2, NULL, 'Rechazado - Llamar para autorizar', '2025-12-16 23:51:28.825', NULL);
